base_channels: 64
batch_size: 128
beta_end: 0.02
beta_start: 0.0001
ckpt_every: 20000
cpu: False
diffusion_steps: 1000
log_every: 10000
lr: 0.0001
max_shift_px: 6
mnist_root: /home/yujincho/.cache/mnist
num_sample_save: 8
num_samples: None
num_workers: 0
output_dir: runs_cDDPM0114/train_full200000
padding_mode: zeros
sample_every: 5000
seed: 42
time_dim: 128
train_steps: 200000
weight_decay: 0.0
